name: RMWC Release

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
  alpha:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    if: contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: git checkout ${{github.head_ref}}
      - run: npm run alpha:patch
        if: contains(github.head_ref, 'alpha')
        env:
          CI: true

  # patch:
  #   runs-on: ubuntu-latest
  #   if: contains(github.ref, 'release/patch')
  #   steps:
  #     - run: echo "Do patch"
  # minor:
  #   runs-on: ubuntu-latest
  #   if: contains(github.ref, 'release/minor')
  #   steps:
  #     - run: echo "Do minor"
  # major:
  #   runs-on: ubuntu-latest
  #   if: contains(github.ref, 'release/major')
  #   steps:
  #     - run: echo "Do major"
